#server
server:
  port: 85
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    
    

#spring
spring:
  datasource:
    url: jdbc:mysql://176.55.9.157:3306/gym?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: false
#配置文件传输
spring.servlet.multipart.enabled: true 
spring.servlet.multipart.file-size-threshold: 0
#单个数据的大小
spring.servlet.multipart.maxFileSize: 100MB
#总数据的大小
spring.servlet.multipart.maxRequestSize: 100MB
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.gym.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

#springmvc
#lOG
logging:
  level:
    com.gy: DEBUG

    
#Thread rool
async-thread-pool:
  corePoolSize: 5
  maximumPoolSize: 10
  keepAliveTime: 30
  
#yml文件配置pagehelper
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  

 

      
    
    
    
    
    
    
